---
- import_playbook: setup-directory.yml
  name: set up working directories

- hosts: iosv
  tasks:
  - template: src=ios/common.j2 dest=configs/{{inventory_hostname}}.txt
    name: create configuration for IOS devices

- hosts: nxos
  tasks:
  - template: src=nxos/common.j2 dest=configs/{{inventory_hostname}}.txt
    name: create configuration for Nexus devices
