---
all:
  hosts:
    dns-server:
    ntp-server:

spines_zurich:
  hosts:
    s1-zh:
    s2-zh:

leafs_zurich:
  hosts:
    bl1-zh:
    l1-zh:
    l2-zh:

edge_zurich:
  hosts:
    bl1-zh:
    fw-zh:

zurich:
  children:
    spines_zurich:
    leafs_zurich:
    edge_zurich:

edge:
  children:
    edge_zurich:

switches:
  children:
    leafs_zurich:
    spines_zurich:
