---
- hosts: all
  tasks:
  - cisco.ios.ios_facts:
      gather_subset: [ interfaces, hardware ]
    when: ansible_network_os == 'ios'

  - junipernetworks.junos.junos_facts:
    when: ansible_network_os == 'junos'

  - arista.eos.eos_facts:
      gather_subset: [ interfaces, hardware ]
    when: ansible_network_os == 'eos'

  - debug: var=vars
