---
all:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: lab
    ansible_ssh_pass: Complex!
ios:
  hosts:
    rtr-ios:
      ansible_host: 192.168.121.201
  vars:
    ansible_network_os: ios
eos:
  hosts:
    sw-eos:
      ansible_host: 192.168.121.200
  vars:
    ansible_network_os: eos
junos:
  hosts:
    sw-junos:
      ansible_host: 172.17.0.2
  vars:
    ansible_network_os: junos
    ansible_connection: ansible.netcommon.netconf
    ansible_port: 22
