---
- hosts: all
  gather_facts: false
  tasks:
  - ansible.netcommon.cli_parse:
      command: "show ip ospf neighbor"
      parser:
        name: ansible.netcommon.textfsm
      set_fact: ip_ospf_neighbor
