---
- hosts: localhost
  name: Create directory
  tasks:
  - name: clean up config directory
    file: path=configs state=absent
    when: config_cleanup is defined
  - name: create config directory
    file: path=configs state=directory