#
# Demonstrate local variables
#
---
- hosts: localhost
  vars:
    dir: /bin
  tasks:
  - name: First in play
    debug: var=dir
  - block:
      - debug: var=dir
        name: Within a block
      - set_fact: dir=/tmp
      - debug: var=dir
        name: Within block, after set_fact
    vars:
      dir: /usr/local/bin
  - name: Outside of block
    debug: var=dir
